server:
  host: "localhost"
  port: 1323

database:
  default: "mysql"
  connections:
    mysql:
      driver: "mysql"
      url: ""
      host: "127.0.0.1"
      port: 3306
      database: "go-microframework"
      username: "admin"
      password: "admin"
      #unix_socket: ""
      charset: "utf8mb4"
      collation: "utf8mb4_unicode_ci"
      prefix: "",
      prefix_indexes: true
      #strict: true
      # engine:
      # options:

queue:
  default: "sync"
  connections:
    sync:
      driver: "sync"
    sqs:
      driver: "sqs"
      key: "AWS_ACCESS_KEY_ID"
      secret: "AWS_SECRET_ACCESS_KEY"
      prefix: "https://sqs.ap-southeast-1.amazonaws.com/your-account-id"
      queue: "your-queue-name"
      region: "ap-southeast-1"